version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: iot_dashboard
      MYSQL_USER: iotuser
      MYSQL_PASSWORD: iotpass
      volumes:
        - db_data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
